export const GET_WALLET_DETAILS_WALLET_FACTORY = "GET_WALLET_DETAILS";
export const GET_CREATED_WALLET_ADDRESS_WALLET_FACTORY = "GET_CREATED_WALLET_ADDRESS";
export const GET_OWNER_WALLET="GET_OWNER";
export const DEPOSIT_WALLET = "DEPOSIT";
export const WITHDRAWAL_WALLET = "WITHDRAWAL";